#!/bin/bash
# This is a simple script to log the user into the runnin gmc320 docker image
# it requires the "SSH & Web Terminal" addon has been installed and
# protection mode be disabled within the addon.

ID=$(docker ps -a | grep gmc3xx_monitor | awk '{ print $1 }')
docker exec -it "${ID}" bash
