name: "GMC 3xx Radiation Monitor"
description: "Radiation Monitor Sensor Interface"
version: "1.0.0"
slug: "gmc3xx_monitor"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  port: "/dev/ttyUSB0"
  baudrate: 115200
  repeat: "60"
schema:
  port: str
  baudrate: int
  repeat: int
init: false
startup: once
uart: true
host_network: true
video: false
homeassistant_api: true
hassio_api: false